################################################################################
#  Licensed to the Apache Software Foundation (ASF) under one
#  or more contributor license agreements.  See the NOTICE file
#  distributed with this work for additional information
#  regarding copyright ownership.  The ASF licenses this file
#  to you under the Apache License, Version 2.0 (the
#  "License"); you may not use this file except in compliance
#  with the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
# limitations under the License.
################################################################################

# We need to specify repo related information here since Apache INFRA doesn't differentiate
# between several workflows with the same names while preparing a report for GHA usage
# https://infra-reports.apache.org/#ghactions
name: Nightly Flink Connector Pulsar
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  compile_and_test:
    if: github.repository_owner == 'apache'
    strategy:
      fail-fast: false
      matrix:
        flink_branches: [{
          flink: 1.18-SNAPSHOT,
          branch: main
        }, {
          flink: 1.19-SNAPSHOT,
          branch: main
        }, {
          flink: 1.20-SNAPSHOT,
          branch: main
        }, {
          flink: 1.18.1,
          branch: v4.1
        }, {
          flink: 1.19.0,
          branch: v4.1
        }]
    uses: apache/flink-connector-shared-utils/.github/workflows/ci.yml@ci_utils
    with:
      jdk_version: ${{ matrix.jdk || '8, 11, 17' }}
      flink_version: ${{ matrix.flink_branches.flink }}
      connector_branch: ${{ matrix.flink_branches.branch }}
      run_dependency_convergence: false
      timeout_global: 120
      timeout_test: 80
